// patient-interface.clean.js — clean patient dashboard script
// Uses sessionStorage.user and sessionStorage.role === 'patient'
(function(){
  'use strict';
  function $id(id){ return document.getElementById(id); }
  function showInlineAlert(containerId, message, kind){ var c = $id(containerId); if(!c) return; c.innerHTML = '<div class="alert '+(kind==='success'?'alert-success':'alert-error')+'">'+message+'</div>'; setTimeout(function(){ if(c) c.innerHTML=''; },3500); }
  function requirePatient(){ try{ var raw = sessionStorage.getItem('user'); var role = sessionStorage.getItem('role'); if(!raw||role!=='patient'){ if(window.ui && ui.showToast) ui.showToast('Please sign in as a patient','default',900); setTimeout(function(){ location.href='Hospital Login page.html?role=patient'; },700); return null;} return JSON.parse(raw);}catch(e){console.warn(e);return null;} }
  function loadDoctors(){ fetch('doctors.json').then(function(r){return r.json();}).then(function(data){ var docs = Array.isArray(data)?data:(data.doctors||[]); populateDoctors(docs); }).catch(function(){ populateDoctors([{id:'1',name:'Dr. Sarah Thompson',specialty:'Cardiology'},{id:'2',name:'Dr. James Patel',specialty:'Neurology'}]); }); }
  function populateDoctors(list){ var sel=$id('doctor-select'); if(!sel) return; sel.innerHTML='<option value="">Choose a doctor...</option>'; list.forEach(function(d){ var o=document.createElement('option'); o.value=d.id||d.name; o.textContent=(d.name||d.first_name)+' - '+(d.specialty||d.specialization||''); sel.appendChild(o); }); }
  function getAppointments(){ try{ return JSON.parse(localStorage.getItem('appointments')||'[]'); }catch(e){return [];} }
  function saveAppointments(list){ localStorage.setItem('appointments', JSON.stringify(list)); }
  function formatDate(d){ try{return new Date(d).toLocaleDateString();}catch(e){return d;} }
  function renderAppointmentsFor(email){ var listEl=$id('appointments-list'); if(!listEl) return; var apps=getAppointments().filter(function(a){return a.userEmail===email;}); listEl.innerHTML=''; if(!apps.length){ listEl.innerHTML='<li class="empty-message">No appointments scheduled yet.</li>'; return;} apps.sort(function(a,b){return new Date(b.date)-new Date(a.date);}); apps.forEach(function(a){ var li=document.createElement('li'); li.className='appointment-item'; var html=''+ '<div>' + '<div style="color:var(--primary); font-weight:600; margin-bottom:6px;">📅 '+formatDate(a.date)+(a.time?(' at '+a.time):'')+'</div>' + '<div style="color:#888; font-size:.95rem;">👨‍⚕️ '+(a.doctorName||a.doctorId)+'</div>' + '</div>' + '<div class="appointment-status">'+(a.status||'Scheduled')+'</div>'; li.innerHTML=html; listEl.appendChild(li); }); }
  document.addEventListener('DOMContentLoaded', function(){ var patient=requirePatient(); if(!patient) return; var displayName=patient.name||patient.firstName||patient.username||patient.email||'Patient'; var nameEl=$id('patient-name'); if(nameEl) nameEl.textContent=displayName; var emailEl=$id('patient-email'); if(emailEl) emailEl.textContent=patient.email||patient.username||''; var logout=$id('logout-btn'); if(logout) logout.addEventListener('click', function(){ sessionStorage.clear(); if(window.ui) ui.showToast('Logged out','default'); setTimeout(function(){ location.href='Hospital Home.html'; },500); }); var homeBtn=$id('homeBtn'); if(homeBtn) homeBtn.addEventListener('click', function(){ location.href='Hospital Home.html'; }); loadDoctors(); var dfield=$id('appointment-date'); if(dfield) dfield.min=new Date().toISOString().split('T')[0]; var bookBtn=$id('book-btn'); if(bookBtn) bookBtn.addEventListener('click', function(){ var doctorSel=$id('doctor-select'); var doctorId=doctorSel?doctorSel.value:''; var date=($id('appointment-date')||{}).value||''; var time=($id('appointment-time')||{}).value||''; if(!doctorId){ showInlineAlert('booking-alert','Please select a doctor','error'); return;} if(!date){ showInlineAlert('booking-alert','Please select a date','error'); return;} var doctorName=(doctorSel&&doctorSel.selectedOptions)?doctorSel.selectedOptions[0].textContent:doctorId; var apps=getAppointments(); var ap={ id:Date.now(), userEmail:patient.email||patient.username||displayName, doctorId:doctorId, doctorName:doctorName, date:date, time:time, status:'Scheduled', createdAt:new Date().toISOString() }; apps.push(ap); saveAppointments(apps); showInlineAlert('booking-alert','Appointment booked successfully!','success'); setTimeout(function(){ if($id('appointment-date')) $id('appointment-date').value=''; if(doctorSel) doctorSel.selectedIndex=0; renderAppointmentsFor(ap.userEmail); },700); }); renderAppointmentsFor(patient.email||patient.username||displayName); });
})();
